dependency 'puppetlabs-stdlib', '>=4.0.0'
dependency 'maestrodev-wget', '>=1.3.0'
name 'conzar-tomcat6'
version '0.1.0'
author 'Michael Speth'
license 'GPLv3'
project_page ''
summary 'Installs and Manages Tomcat6'
description 'Installs and Manages Tomcat6'
