dependency 'puppetlabs-stdlib', '>=4.0.0'
dependency 'maestrodev-wget', '>=1.3.0'
dependency 'conzar/checkrun', '>=0.2.1'
name 'conzar-tomcat6'
version '0.1.0'
author 'Michael Speth'
license 'GPLv3'
project_page 'https://github.com/Conzar/conzar-tomcat6'
summary 'Installs and Manages Tomcat6'
description 'Installs and Manages Tomcat6'
source 'https://github.com/Conzar/conzar-tomcat6/tree/master/'
